### ISSUE TITLE
Change meta theme-color with dark theme

### ISSUE THREAD

**Issue by janispritzkau** [victorheringer/planning-poker-deck#1]
When using a dark theme Chrome's header or the status bar in standalone mode is still white. Setting the meta theme-color tag to the background color would result in a better looking app.

**Comment by victorheringer** [comment]
Hi @janispritzkau thanks for the comment and sorry about the delay to respond. I had to stop maintaining this project for while but I'm back! Yeah this makes totally sense, I'll ship a fix for this asap!

**Comment by victorheringer** [comment]
Fixed at v2.0.0(479e3c544abb620e28f8916029787ccf8222a853)
